export const SUPPORTED_RADIOS: RadioDefinition[] = [
  {
    id: "flyskyel18",
    name: "Flysky EL18",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.8",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 480,
  },
  {
    id: "flyskeynb4plus",
    name: "Flysky NB4+",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.11",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 480,
  },
  {
    id: "flyskynv14",
    name: "Flysky NV14",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.5",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 480,
  },
  {
    id: "flyskypa01",
    name: "Flysky PA01",
    display: "color",
    hasTouch: false,
    minSupportedVersion: "2.11",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 240,
  },
  {
    id: "flyskypl18",
    name: "Flysky PL18 / PL18EV",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 480,
  },
  {
    id: "flyskypl18u",
    name: "Flysky PL18U",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.11",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 480,
  },
  {
    id: "flyskyst16",
    name: "Flysky ST16",
    display: "color",
    hasTouch: false,
    minSupportedVersion: "2.11",
    maxSupportedVersion: null,
    screenWidth: 320,
    screenHeight: 480,
  },

  {
    id: "jumperbumblebee",
    name: "Jumper Bumblebee",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpertlite",
    name: "Jumper T-Lite / T-Lite v2",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.4",
    maxSupportedVersion: "2.11",
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpertpro",
    name: "Jumper T-Pro",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.6",
    maxSupportedVersion: "2.11",
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpertprov2",
    name: "Jumper T-Pro v2",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpertpros",
    name: "Jumper T-Pro S",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpert12",
    name: "Jumper T12 / T12 Plus / T12 Pro Hall",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.4",
    maxSupportedVersion: "2.11",
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpert12max",
    name: "Jumper T12 Max",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpert14",
    name: "Jumper T14",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpert15",
    name: "Jumper T15",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 480,
    screenHeight: 320,
  },
  {
    id: "jumpert15pro",
    name: "Jumper T15 Pro",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.12",
    maxSupportedVersion: null,
    screenWidth: 480,
    screenHeight: 320,
  },
  {
    id: "jumpert16",
    name: "Jumper T16 / T16 Plus / T16 Pro Hall",
    display: "color",
    hasTouch: false,
    minSupportedVersion: "2.4",
    maxSupportedVersion: null,
    screenWidth: 480,
    screenHeight: 272,
  },
  {
    id: "jumpert18",
    name: "Jumper T18 / T18 Lite / T18 Pro",
    display: "color",
    hasTouch: false,
    minSupportedVersion: "2.4",
    maxSupportedVersion: null,
    screenWidth: 480,
    screenHeight: 272,
  },
  {
    id: "jumpert20",
    name: "Jumper T20",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "jumpert20v2",
    name: "Jumper T20 V2",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },

  {
    id: "radiomaster-boxer",
    name: "RadioMaster Boxer",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.8",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-gx12",
    name: "RadioMaster GX12",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.11",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-mt12",
    name: "RadioMaster MT12",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-pocket",
    name: "RadioMaster Pocket",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.10",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-t8pro",
    name: "RadioMaster T8 Pro",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.4",
    maxSupportedVersion: "2.11",
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-tx12",
    name: "RadioMaster TX12",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.4",
    maxSupportedVersion: "2.11",
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-tx12mkii",
    name: "RadioMaster TX12 MK2",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.8",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
  {
    id: "radiomaster-tx15",
    name: "RadioMaster TX15",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.12",
    maxSupportedVersion: null,
    screenWidth: 480,
    screenHeight: 320,
  },
  {
    id: "radiomaster-tx16s",
    name: "RadioMaster TX16S / MAX / MK2",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.4",
    maxSupportedVersion: null,
    screenWidth: 480,
    screenHeight: 272,
  },
  {
    id: "radiomaster-tx16smk3",
    name: "RadioMaster TX16S MK3",
    display: "color",
    hasTouch: true,
    minSupportedVersion: "2.12",
    maxSupportedVersion: null,
    screenWidth: 800,
    screenHeight: 480,
  },
  {
    id: "radiomaster-zorro",
    name: "RadioMaster Zorro",
    display: "bw",
    hasTouch: false,
    minSupportedVersion: "2.6",
    maxSupportedVersion: null,
    screenWidth: 128,
    screenHeight: 64,
  },
];
